#!/bin/sh

preprocessed=`mktemp`.c
gcc -E "$1" > $preprocessed
gcc -g $preprocessed

nmlist=`mktemp`
global=`nm -l a.out | grep ":" | grep "[0-8] [^T]" | tee $nmlist | wc -l`
echo "global variables found:" $global
cat $nmlist
echo "============================"
cc1=`grep -w -E "(if)|(case)|(while)|(for)" -o $preprocessed | wc -l`
echo "if case while for found:" $cc1
grep -w -E "(if)|(case)|(while)|(for)" $preprocessed
echo "============================"
cc2=`grep -E "(\?)|(&&)|(\|\|)" -o $preprocessed | wc -l`
echo "? && || found:" $cc2
grep -E "(\?)|(&&)|(\|\|)" $preprocessed
echo "============================"
echo "estimated cyclomatic complexity: " $(( $cc1 + $cc2 ))
echo "============================"
goto=`grep -w -E "goto" -o $preprocessed | wc -l`
echo "goto found:" $goto
grep -w -E "goto" $preprocessed

