#!/bin/sh

gcc -g "$1"
echo "global variables found:"
nm -l a.out | grep ":" | grep "[0-8] [^T]" | tee global.tmp | wc -l
cat global.tmp
echo "============================"
echo "if case while for found:"
grep -w -E "(if)|(case)|(while)|(for)" -o "$1" | wc -l
grep -w -E "(if)|(case)|(while)|(for)" "$1" 
echo "============================"
echo "? && || found:"
grep -E "(\?)|(&&)|(\|\|)" -o "$1" | wc -l
grep -E "(\?)|(&&)|(\|\|)" "$1"

