#!/bin/sh

filename=$1
# ## removes the longest matching prefix as *.
# and leaves the suffix
suffix=${filename##*.}
echo "suffix" $suffix

if [ $suffix = "c" ]
then
    compiler="gcc"
    preprocessed=`mktemp`.c
    includeremoved=`mktemp`.c
    sed "s/#include\s*<.*>//" "$filename" > $includeremoved
    $compiler -E $includeremoved > $preprocessed
    trimmed=$preprocessed
elif [ $suffix = "cc" ]
then
    compiler="g++"
    preprocessed=`mktemp`.cc
    includeremoved=`mktemp`.c
    sed "s/#include\s*<.*>//" "$filename" > $includeremoved
    $compiler -E $includeremoved > $preprocessed
    trimmed=$preprocessed
else
    echo "unknown suffix" $suffix
    exit
fi

$compiler -g $filename
nmlist=`mktemp`
global=`nm -l a.out | grep ":" | grep "[0-8] [^T]" | awk '{sub(/^.*\//, "", $4); print $3 " in " $4}' | tee $nmlist | wc -l`
echo "global variables found:" $global
cat $nmlist
echo "============================"
cc1=`grep -w -E "(if)|(case)|(while)|(for)" -o $trimmed | wc -l`
echo "if case while for found:" $cc1
grep -w -E "(if)|(case)|(while)|(for)" $trimmed
echo "============================"
cc2=`grep -E "(\?)" -o $trimmed | wc -l`
echo "? found:" $cc2
grep -E "(\?)|(&&)|(\|\|)" $trimmed
echo "============================"
echo "estimated cyclomatic complexity:" $(( $cc1 + $cc2 ))
echo "============================"
goto=`grep -w -E "goto" -o $trimmed | wc -l`
echo "goto found:" $goto
grep -w -E "goto" $trimmed
echo "============================"
longest=`awk ' { if ( length > x ) { x = length} }END{ print x }' $filename`
echo "the lenghth of the longest line:" $longest

